### ISSUE TITLE
Spamming Log with Compat Ender Dragon Fight Remaster / Fabric 1.21.1 with 0.16.7 (Hug Modpack)

### ISSUE THREAD

**Issue by suerion** [DrexHD/MeliusCommands#3]
Hey, on my huge modpack, melius commands does spamm the logs with an lot warning

https://mclo.gs/92TDbmG

```
[18:03:34] [Server thread/WARN]: Failed to execute function endfight:tick
java.lang.IllegalStateException: End size 751 is less than fixed size 752
	at java.base/java.util.stream.Nodes$FixedNodeBuilder.end(Nodes.java:1241) ~[?:?]
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at knot/net.minecraft.class_269.method_1178(class_269.java:195) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2233.method_9457(class_2233.java:109) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2233.method_9450(class_2233.java:67) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2233.method_9449(class_2233.java:63) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3115.method_13579(class_3115.java:213) ~[server-intermediary.jar:?]
	at knot/com.mojang.brigadier.context.ContextChain.mixinextras$bridge$run$9(ContextChain.java) ~[brigadier-1.3.10.jar:?]
	at knot/com.mojang.brigadier.context.ContextChain.wrapOperation$ffa000$melius-commands$runConditionally(ContextChain.java:562) ~[brigadier-1.3.10.jar:?]
	at knot/com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
	at knot/net.minecraft.class_8865.method_54416(class_8865.java:29) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8865.execute(class_8865.java:13) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8856.method_54405(class_8856.java:8) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8847.method_54388(class_8847.java:8) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8854.method_54390(class_8854.java:107) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2170.method_54313(class_2170.java:379) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2991.method_12904(class_2991.java:69) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2991.method_29460(class_2991.java:59) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2991.method_18699(class_2991.java:53) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1007) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3176.method_3813(class_3176.java:299) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by DrexHD** [comment]
What makes you think this error is caused by `MeliusCommands`? Are you sure this doesn't happen without the mod installed, and is reproducible with the mod installed. I don't see how this mod could cause that error. Just because a mod is mentioned in a stack trace doesn't mean it is the cause of an error.

**Comment by suerion** [comment]
i had added only Meliuscommands and tried it, but this error ocours, thats why i thougt, the error got from melius commands, but i could also disable the mod again, and try if it occurs again.
